### ISSUE TITLE
关于导航栏在移动端显示不佳问题

### ISSUE THREAD

**Issue by SmRiley** [BeiYinZhiNian/Caviar-Blazor#2]
虽然项目中会根据设备大小选择侧边栏隐藏时的大小,但是移动端设备显示时侧边栏会挤压body内容,在antd pro与antd docs 中都采用了移动端中显示为抽屉的方式.建议跟进.
![image](https://user-images.githubusercontent.com/45205313/142766306-8eaff21f-9e47-4473-83fa-9cc7076abe4a.png)
![image](https://user-images.githubusercontent.com/45205313/142766309-0205962a-64c0-4626-9547-3795acb9c3d0.png)

**Comment by BeiYinZhiNian** [comment]
谢谢，新版会就此进行改进

**Comment by BeiYinZhiNian** [comment]
新版已将此问题进行改进，请浏览 [小屏幕自动使用遮罩，使手机端的体验更好](https://github.com/BeiYinZhiNian/Caviar-Blazor/commit/d1501976903b1082c68ccbdfe38aee7066123b42)
